export const eventsActionTypes = {
    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
    INSERT_EVENT_REQUEST: 'INSERT_EVENT_REQUEST',
    INSERT_EVENT_SUCCESS: 'INSERT_EVENT_SUCCESS',
    INSERT_EVENT_ERROR: 'INSERT_EVENT_ERROR',
    IGNORE_REPORT_EVENT_REQUEST: 'IGNORE_REPORT_EVENT_REQUEST',
    IGNORE_REPORT_EVENT_SUCCESS: 'IGNORE_REPORT_EVENT_SUCCESS',
    IGNORE_REPORT_EVENT_ERROR: 'IGNORE_REPORT_EVENT_ERROR',
    DELETE_DATA_REQUEST: 'DELETE_DATA_REQUEST',
    DELETE_DATA_REQUEST_SUCCESS: 'DELETE_DATA_REQUEST_SUCCESS',
    DELETE_DATA_REQUEST_ERROR: 'DELETE_DATA_REQUEST_ERROR',
    UPDATE_DATA_REQUEST: 'UPDATE_DATA_REQUEST',
    UPDATE_DATA_REQUEST_SUCCESS: 'UPDATE_DATA_REQUEST_SUCCESS',
    UPDATE_DATA_REQUEST_ERROR: 'UPDATE_DATA_REQUEST_ERROR'
}