export const eventsActionTypes = {
    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
    IGNORE_REPORT_EVENT_REQUEST: 'IGNORE_REPORT_EVENT_REQUEST',
    IGNORE_REPORT_EVENT_SUCCESS: 'IGNORE_REPORT_EVENT_SUCCESS',
    IGNORE_REPORT_EVENT_ERROR: 'IGNORE_REPORT_EVENT_ERROR'
}